### ISSUE TITLE
Stackframe data is not available on threadpool threads

### ISSUE THREAD

**Issue by borgdylan** [mono/debugger-libs#106]
The VSCode debugger for Mono has recently switched to using nuget packages built from this repo. I am observing that while debugging a thread that is not the main thread, I get no stackframe information and the debugger seems to not notice the line number for the breakpoint it is currently paused at.

**Comment by DavidKarlas** [comment]
This sounds more like bug that would need fixing in https://github.com/Microsoft/vscode-mono-debug, since this works fine in Visual Studio for Mac.

Also it's possible that this happens if other threads are in native code.
