### ISSUE TITLE
Consolidate Roslyn nuget versions with MD

### ISSUE THREAD

**Issue by Therzok** [mono/debugger-libs#178]
Currently uses 1.3.2, bump to 2.7.0

**Comment by joj** [comment]
Please let me check what VS is using before meeting this in. If could make VS incompatible with debugger libs.

**Comment by joj** [comment]
*merging

**Comment by Therzok** [comment]
@joj sure thing, but given various VS versions also apply binding redirects, they should be ok.

**Comment by joj** [comment]
Agreed. I meant to check that too.

**Comment by joj** [comment]
VS is shipping with 2.7.0 and binding to that too, so I'm ok with this :D
