### ISSUE TITLE
Mono.Debugger.Soft references Microsoft.SymbolStore and Microsoft.FileFormats which don't exist on nuget.or

### ISSUE THREAD

**Issue by CartBlanche** [mono/debugger-libs#389]
I was just trying to update our dependencies on `Mono.Debug*`, to the latest version on `main`. 
When I try to build `debugger-libs.sln` it tells me these 2 packages don't exist/can't be found. I checked on nuget.org and they are not there either. So `Mono.Debugger.Soft.csproj` does not compile.

```
<PackageReference Include="Microsoft.SymbolStore" Version="1.0.411401" />
<PackageReference Include="Microsoft.FileFormats" Version="1.0.411401" />
```

Any suggestions?

**Comment by CartBlanche** [comment]
@thaystg You seem to have added these dependences 2 months ago (https://github.com/mono/debugger-libs/commit/4b04e4e9dc0375001965e40c953e0cbe67c4e49c). 
How do we access these new packaged if they are not published on nuget.org ?

**Comment by thaystg** [comment]
Can you use from this feed?
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

**Comment by CartBlanche** [comment]
@thaystg sure, it would just be nice if it just compiled out of the box :) Would a nuget.config help here?
