### ISSUE TITLE
Race in DebugSymbolsManager.cs

### ISSUE THREAD

**Issue by daltzctr** [mono/debugger-libs#410]
https://github.com/mono/debugger-libs/blob/df3b584b31ab7c53206631097d0e1be9d47e3286/Mono.Debugging.Soft/DebugSymbolsManager.cs#L145-L193 mutates the collection after an await, making it unsafe.

In certain circumstances in a MAUI android project, this results in a crash.

**Comment by grendello** [comment]
The entire class has entry points which can interfere with each other, access to `symbolsByAssembly` should be protected by a lock,at the very least.
